# Generated by Django 2.2.5 on 2019-09-15 20:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state_active', models.BooleanField(default=False)),
                ('mailing_list', models.CharField(max_length=200)),
                ('source_sites', multiselectfield.db.fields.MultiSelectField(choices=[('http://www.avito.ru', 'Avito'), ('http://www.move.ru', 'Move'), ('http://www.arendator.ru', 'Arendator'), ('http://www.mirkvartir.ru', 'Mirkvartir'), ('http://www.sob.ru', 'Sob'), ('http://www.zdanie.info', 'Zdanie'), ('http://www.moskva.gde.ru', 'MoskvaGde'), ('http://www.propokupki.ru', 'Propokupki'), ('http://www.kvmeter.ru', 'KvMeter'), ('http://www.comrent.ru', 'Comrent')], max_length=222)),
                ('objects_amount', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (50, 50), (100, 100)])),
                ('objects_types', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Аренда'), (1, 'Продажа')], max_length=3)),
                ('min_price_rent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_price_rent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('min_price_sell', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_price_sell', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('starting_time', models.TimeField()),
                ('updating_period', models.IntegerField(choices=[(900, '15 минут'), (3600, '1 час'), (10800, '3 часа'), (86400, '1 сутки')])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
