# Generated by Django 2.2.4 on 2019-09-12 15:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('source', multiselectfield.db.fields.MultiSelectField(choices=[('http://www.avito.ru', 'Avito'), ('http://www.move.ru', 'Move'), ('http://www.arendator.ru', 'Arendator'), ('http://www.mirkvartir.ru', 'Mirkvartir'), ('http://www.sob.ru', 'Sob'), ('http://www.zdanie.info', 'Zdanie'), ('http://www.moskva.gde.ru', 'MoskvaGde'), ('http://www.propokupki.ru', 'Propokupki'), ('http://www.kvmeter.ru', 'KvMeter'), ('http://www.comrent.ru', 'Comrent')], max_length=222)),
                ('min_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('email', models.CharField(max_length=200)),
                ('objects_amount', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (50, 50), (100, 100)])),
                ('starting_time', models.TimeField()),
                ('updating_period', models.IntegerField(choices=[(900, '15 min'), (3600, '1 hour'), (10800, '3 hours'), (86400, '1 day')])),
                ('objects_type', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Rent'), (1, 'Sell')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
