# Generated by Django 2.2.5 on 2019-10-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(choices=[('Moscow', 'Москва'), ('Barnaul', 'Барнаул')], max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updating_period',
            field=models.IntegerField(choices=[(5, '5 секунд'), (900, '15 минут'), (3600, '1 час'), (10800, '3 часа'), (86400, '1 сутки')]),
        ),
    ]
