# Generated by Django 2.2.4 on 2019-09-13 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
