# Generated by Django 2.2.5 on 2019-10-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191001_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='task_id',
            field=models.IntegerField(default=-1),
        ),
    ]
