# Generated by Django 2.2.5 on 2019-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191015_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='updating_period',
            field=models.IntegerField(choices=[(5, '5 сек'), (60, '1 минута'), (900, '15 минут'), (3600, '1 час'), (10800, '3 часа'), (86400, '1 сутки')]),
        ),
    ]
